### ISSUE TITLE
Is this suitable for querying from my webpage?

### ISSUE THREAD

**Issue by vikrambajaj22** [cmungall/owljs#6]
I have an ontology (.owl file) created using Protege. How do I use this library to run SPARQL queries/DL queries on my ontology (which is uploaded on my website) from another website that I am building?

**Comment by cmungall** [comment]
This library uses ringo-js, which only works server side, so the only way to use it from a webpage is to wrap it in a service. I wouldn't recommend this.

If you do want to go a service route, I personally favor https://github.com/phenoscape/owlery which will handle DL queries and (I think) SPARQL.

There are some packages like
https://www.npmjs.com/package/sparql
But these seem to assume a SPARQL endpoint, you want to query an in-memory ontology?

I'll close as its out of scope for this lib (which is not supported in any case, unfortunately the ringo-js route turned out not to be the best)

**Comment by vikrambajaj22** [comment]
Thanks for replying! I'll check out the links that you've suggested then :)
The ontology has been uploaded on my website already. I just need to query it and return the results to another webpage that I am building :)
